In [11]:
import pandas as pd

employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [12]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [13]:
pd.merge(employees, departments, on="DeptID") #inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [14]:
pd.merge(employees, departments, on="DeptID", how="left").fillna("None") #left join with fill

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30         None

In [15]:
pd.merge(employees, departments, on="DeptID", how="right").fillna("None") #right join with fill

  EmpID   Name  DeptID     DeptName
0   1.0  Alice      10           HR
1   2.0    Bob      20  Engineering
2  None   None      40    Marketing

In [17]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})
 
pd.concat([df1, df2], axis=1)

    Name     Name
0  Alice  Charlie
1    Bob    David